name: NickFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 5.4
description: Plugin for the NickFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, ItsTeeqo_]

# plugin.yml is no longer used to define commands.
